import type { Metadata } from "next";
import "./globals.css";
import Navegation from "@/components/layout/Navigation";
import Footer from "@/components/layout/Footer";
import { Poppins } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={poppins.variable}>
      <body>
        <Navegation />
        <main className="pt-17 md:pt-21">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
